import './globals.css'
import Link from 'next/link'
import { Control } from './Control'

export const metadata = {
  title: 'Next Tutorials',
  description: 'Generated by create next app',
}

export default async  function RootLayout({ children }) {
  const res = await fetch('http://localhost:4000/topics', { next: { revalidate: 0 }});
  const topics = await res.json();
  return (
    <html lang="en">
        <body >
        <h1><Link href='/'>Hi</Link></h1>
        <ol>
          {/* <li><Link href='/reda/1'>html</Link></li>
          <li><Link href='/reda/2'>css</Link></li> */}
          {
            topics.map((topic) => {
              return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
            })
          }
        </ol>
          {children}
          <Control />
      </body>
    </html>
  )
}
